import { Template, TemplateField } from '../types/template';

/**
 * Helper for official Saudi ID card text fields.
 * Coordinates were measured pixel-by-pixel against the reference card screenshots
 * (registered onto the 952x578 blank templates). `y` is the text BASELINE (alphabetic),
 * so values sit exactly on the same line as the printed labels regardless of glyph shapes.
 */
const cardText = (
  id: string,
  name: string,
  key: string,
  x: number,
  y: number,
  zIndex: number,
  opts: Partial<TemplateField> = {}
): TemplateField => ({
  id,
  name,
  key,
  type: 'text',
  x,
  y,
  width: 30,
  fontFamily: 'Frutiger LT Arabic',
  fontSize: 19.5,
  fontWeight: '700',
  fontStyle: 'normal',
  color: '#111111',
  textAlign: 'right',
  textTransform: 'none',
  letterSpacing: 0,
  lineHeight: 1.2,
  textBaseline: 'alphabetic',
  opacity: 1,
  zIndex,
  ...opts,
});

const cardPhoto = (id: string): TemplateField => ({
  // Personal Photo in the left white box (exact frame: 62px to 298px, 144px to 424px on 952x578 template)
  id,
  name: 'الصورة الشخصية (Photo)',
  key: 'photo',
  type: 'image',
  x: 18.9076, // 180 / 952 * 100
  y: 49.1349, // 284 / 578 * 100
  width: 24.7899, // 236 / 952 * 100
  height: 48.4429, // 280 / 578 * 100
  fontFamily: 'Almarai',
  fontSize: 12,
  fontWeight: '400',
  fontStyle: 'normal',
  color: '#000000',
  textAlign: 'center',
  textTransform: 'none',
  letterSpacing: 0,
  lineHeight: 1,
  opacity: 1,
  imageShape: 'rect',
  zIndex: 1,
});

// Shared name block: Arabic name in Noto Naskh Arabic Bold (exact match for official Saudi cards),
// English name in Arial Regular with refined size and contrast so it is not overly bold.
const NAME_AR_STYLE: Partial<TemplateField> = {
  width: 60,
  fontFamily: 'Noto Naskh Arabic',
  fontSize: 32.5,
  fontWeight: '700',
  color: '#141414',
};
const NAME_EN_STYLE: Partial<TemplateField> = {
  width: 62,
  fontFamily: 'Arial',
  fontSize: 24.5,
  fontWeight: '700',
  color: '#111111',
  textAlign: 'right',
  textTransform: 'uppercase',
  letterSpacing: 0.35,
};

// Driving license columns: English values start right after the English labels,
// Arabic values end right before the Arabic labels.
const DL_EN_X = 47.10; // left edge
const DL_AR_X = 83.21; // right edge
const DL_EN: Partial<TemplateField> = { fontFamily: 'Arial', fontWeight: '700', fontSize: 18.5, color: '#111111', textAlign: 'left' };
// Simplified Arabic is used for numeric fields because its Eastern Arabic numeral glyphs
// (especially ٠ zero) exactly match what appears on the official Saudi Iqama and driving license.
const DL_AR_DIGITS: Partial<TemplateField> = { fontFamily: 'Simplified Arabic', fontSize: 22.0, fontWeight: '700', color: '#0f0f0f' };

export const SAUDI_DRIVING_LICENSE_TEMPLATE: Template = {
  id: 'saudi-driving-license',
  name: 'رخصة سياقة - Driving License',
  category: 'badge',
  imageUrl: '/templates/saudi-driving-license-blank.jpg',
  naturalWidth: 952,
  naturalHeight: 578,
  createdAt: Date.now(),
  fields: [
    cardPhoto('dl-photo'),

    // Names
    cardText('dl-name-ar', 'الاسم بالعربية (Arabic Name)', 'nameAr', 94.54, 27.60, 2, NAME_AR_STYLE),
    cardText('dl-name-en', 'الاسم بالإنجليزية (English Name)', 'nameEn', 94.54, 34.80, 3, NAME_EN_STYLE),

    // Row 1: ID Number
    cardText('dl-id-en', 'ID Number (EN)', 'idNumberEn', DL_EN_X, 42.72, 4, { ...DL_EN, fontSize: 19.0 }),
    cardText('dl-id-ar', 'رقم الهوية (AR)', 'idNumberAr', DL_AR_X, 42.72, 5, DL_AR_DIGITS),

    // Row 2: License Type
    cardText('dl-lictype-en', 'License Type (EN)', 'licenseTypeEn', 48.42, 51.37, 6, { ...DL_EN, fontSize: 17.5, width: 32 }),
    cardText('dl-lictype-ar', 'نوع الرخصة (AR)', 'licenseTypeAr', 83.38, 51.37, 7, { fontSize: 21.0, fontWeight: '700' }),

    // Row 3: Issue Date
    cardText('dl-issue-en', 'Issue Date (EN)', 'issueDateEn', DL_EN_X, 59.48, 8, DL_EN),
    cardText('dl-issue-ar', 'تاريخ الإصدار (AR)', 'issueDateAr', 83.05, 59.48, 9, DL_AR_DIGITS),

    // Row 4: Date of Birth
    cardText('dl-dob-en', 'Date of Birth (EN)', 'dobEn', 48.53, 67.85, 10, DL_EN),
    cardText('dl-dob-ar', 'تاريخ الميلاد (AR)', 'dobAr', 82.88, 67.85, 11, DL_AR_DIGITS),

    // Row 5: Nationality
    cardText('dl-nation-en', 'Nationality (EN)', 'nationalityEn', DL_EN_X, 76.78, 12, { ...DL_EN, fontSize: 19.0 }),
    cardText('dl-nation-ar', 'الجنسية (AR)', 'nationalityAr', 83.38, 76.78, 13, { fontSize: 20.5, fontWeight: '700' }),

    // Row 6: Expiry Date
    cardText('dl-exp-en', 'Expiry Date (EN)', 'expiryDateEn', DL_EN_X, 84.62, 14, DL_EN),
    cardText('dl-exp-ar', 'تاريخ الانتهاء (AR)', 'expiryDateAr', 83.05, 84.62, 15, DL_AR_DIGITS),

    // Row 7: Blood Type
    cardText('dl-blood-en', 'Blood Type (EN)', 'bloodType', 46.95, 90.83, 16, { ...DL_EN, fontSize: 19.5, fontWeight: '700', color: '#0f0f0f', width: 18 }),
    cardText('dl-blood-ar', 'فصيلة الدم (AR)', 'bloodType', 83.38, 90.83, 17, {
      fontFamily: 'Arial',
      fontWeight: '700',
      fontSize: 19.5,
      color: '#0f0f0f',
      width: 18,
    }),
  ],
};

export const SAUDI_MUQEEM_ID_TEMPLATE: Template = {
  id: 'saudi-muqeem-id',
  name: 'هوية مقيم - Muqeem ID',
  category: 'badge',
  imageUrl: '/templates/saudi-muqeem-id-blank.jpg',
  naturalWidth: 952,
  naturalHeight: 578,
  createdAt: Date.now(),
  fields: [
    cardPhoto('mq-photo'),

    // Names
    cardText('mq-name-ar', 'الاسم بالعربية (Arabic Name)', 'nameAr', 94.54, 27.85, 2, NAME_AR_STYLE),
    cardText('mq-name-en', 'الاسم بالإنجليزية (English Name)', 'nameEn', 94.54, 35.10, 3, NAME_EN_STYLE),

    // Middle column
    // Expiry date is numeric → Simplified Arabic for correct ٠ glyph
    cardText('mq-expiry', 'تاريخ الانتهاء (Expiry Date)', 'expiryDateAr', 48.42, 45.42, 4, { fontFamily: 'Simplified Arabic', fontSize: 22.5, fontWeight: '700', width: 25 }),
    cardText('mq-pob', 'مكان الميلاد (Place of Birth)', 'pobAr', 48.58, 51.90, 5, { fontSize: 20.0, fontWeight: '700', width: 25 }),
    cardText('mq-rel', 'الديانة (Religion)', 'religionAr', 48.58, 58.48, 6, { fontSize: 20.0, fontWeight: '700', width: 25 }),

    // Right column — numeric fields use Simplified Arabic for correct Eastern Arabic numerals
    cardText('mq-id', 'رقم الهوية (ID Number)', 'idNumberAr', 83.54, 45.42, 7, { fontFamily: 'Simplified Arabic', fontSize: 22.5, fontWeight: '700' }),
    cardText('mq-dob', 'تاريخ الميلاد (Date of Birth)', 'dobAr', 83.21, 51.90, 8, { fontFamily: 'Simplified Arabic', fontSize: 22.5, fontWeight: '700' }),
    cardText('mq-nation', 'الجنسية (Nationality)', 'nationalityAr', 83.38, 58.48, 9, { fontSize: 20.0, fontWeight: '700', width: 25 }),
    cardText('mq-job', 'المهنة (Profession)', 'professionAr', 83.54, 65.22, 10, { fontSize: 18.5, fontWeight: '700', width: 40 }),
    cardText('mq-empid', 'هوية صاحب العمل (Employer ID)', 'employerIdAr', 77.30, 71.11, 11, { fontFamily: 'Simplified Arabic', fontSize: 22.5, fontWeight: '700' }),
    cardText('mq-issueplace', 'مكان الإصدار (Place of Issue)', 'issuePlaceAr', 82.72, 78.37, 12, { fontSize: 19.0, fontWeight: '700', width: 45 }),
    cardText('mq-workplace', 'مكان العمل (Place of Work)', 'workPlaceAr', 82.88, 84.60, 13, { fontSize: 20.0, fontWeight: '700', width: 35 }),
    cardText('mq-empname', 'اسم صاحب العمل (Employer Name)', 'employerNameAr', 77.80, 91.18, 14, { fontSize: 19.5, fontWeight: '700', width: 45 }),
  ],
};

export const SAUDI_DRIVER_CARD_TEMPLATE: Template = {
  id: 'saudi-tga-driver-card',
  name: 'بطاقة سائق - Saudi TGA Driver Card',
  category: 'badge',
  imageUrl: '/templates/saudi-driver-card-blank.png',
  naturalWidth: 708,
  naturalHeight: 1024,
  createdAt: Date.now(),
  fields: [
    // Top Header Card Subtitle: "بطاقة رقم 38.00057886" centered at x=50.0%
    {
      id: 'f-tga-topcardno',
      name: 'رقم البطاقة العلوي (Header Card Number)',
      key: 'code',
      type: 'text',
      x: 50.0,
      y: 13.8,
      width: 40,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#64748b',
      textAlign: 'center',
      textTransform: 'none',
      letterSpacing: 0.2,
      lineHeight: 1.2,
      opacity: 1,
      prefix: 'بطاقة رقم ',
      zIndex: 2,
    },

    // SECTION 1: Driver Card Info / بيانات بطاقة السائق
    // Row 1: Driver Card Number (y: 27.54%)
    {
      id: 'f-tga-cardno-en',
      name: 'Card Number (EN)',
      key: 'code',
      type: 'text',
      x: 25.42,
      y: 27.54,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 3,
    },
    {
      id: 'f-tga-cardno-ar',
      name: 'رقم بطاقة السائق (AR)',
      key: 'code',
      type: 'text',
      x: 74.5,
      y: 27.54,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 4,
    },

    // Row 2: Driver Name (y: 30.2%)
    {
      id: 'f-tga-name-en',
      name: 'Driver Name (Left)',
      key: 'name',
      type: 'text',
      x: 25.42,
      y: 30.2,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 5,
    },
    {
      id: 'f-tga-name-ar',
      name: 'اسم السائق (Right)',
      key: 'name',
      type: 'text',
      x: 74.5,
      y: 30.2,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 6,
    },

    // Row 3: Driver Id / رقم هوية السائق (y: 32.42%)
    {
      id: 'f-tga-id-en',
      name: 'Driver Id (EN)',
      key: 'driverId',
      type: 'text',
      x: 25.42,
      y: 32.42,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 7,
    },
    {
      id: 'f-tga-id-ar',
      name: 'رقم هوية السائق (AR)',
      key: 'driverId',
      type: 'text',
      x: 74.5,
      y: 32.42,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 8,
    },

    // Row 4: Issue Date / تاريخ الإصدار (y: 34.86%)
    {
      id: 'f-tga-issue-en',
      name: 'Issue Date (EN)',
      key: 'date',
      type: 'text',
      x: 25.42,
      y: 34.86,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 9,
    },
    {
      id: 'f-tga-issue-ar',
      name: 'تاريخ الإصدار (AR)',
      key: 'date',
      type: 'text',
      x: 74.5,
      y: 34.86,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 10,
    },

    // Row 5: Expiration Date / تاريخ الانتهاء (y: 37.4%)
    {
      id: 'f-tga-expiry-en',
      name: 'Expiration Date (EN)',
      key: 'expiryDate',
      type: 'text',
      x: 25.42,
      y: 37.4,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 11,
    },
    {
      id: 'f-tga-expiry-ar',
      name: 'تاريخ الانتهاء (AR)',
      key: 'expiryDate',
      type: 'text',
      x: 74.5,
      y: 37.4,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 12,
    },

    // Row 6: Card Category / تصنيف البطاقة (y: 40.04%)
    {
      id: 'f-tga-cat-en',
      name: 'Card Category (EN)',
      key: 'cardCategoryEn',
      type: 'text',
      x: 25.42,
      y: 40.04,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 13,
    },
    {
      id: 'f-tga-cat-ar',
      name: 'تصنيف البطاقة (AR)',
      key: 'cardCategoryAr',
      type: 'text',
      x: 74.5,
      y: 40.04,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 14,
    },

    // SECTION 2: License and Company Info / بيانات المنشأة و الترخيص
    // Row 1: License Number / رقم الترخيص (y: 53.61%)
    {
      id: 'f-tga-licno-en',
      name: 'License Number (EN)',
      key: 'licenseNumber',
      type: 'text',
      x: 25.42,
      y: 53.61,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 15,
    },
    {
      id: 'f-tga-licno-ar',
      name: 'رقم الترخيص (AR)',
      key: 'licenseNumber',
      type: 'text',
      x: 74.5,
      y: 53.61,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 16,
    },

    // Row 2: License City / مدينة الترخيص (y: 56.15%)
    {
      id: 'f-tga-city-en',
      name: 'License City (EN)',
      key: 'cityEn',
      type: 'text',
      x: 25.42,
      y: 56.15,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 17,
    },
    {
      id: 'f-tga-city-ar',
      name: 'مدينة الترخيص (AR)',
      key: 'cityAr',
      type: 'text',
      x: 74.5,
      y: 56.15,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 18,
    },

    // Row 3: License Issue Date / تاريخ الإصدار (y: 58.59%)
    {
      id: 'f-tga-licissue-en',
      name: 'License Issue Date (EN)',
      key: 'licenseIssueDate',
      type: 'text',
      x: 25.42,
      y: 58.59,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 19,
    },
    {
      id: 'f-tga-licissue-ar',
      name: 'تاريخ إصدار الترخيص (AR)',
      key: 'licenseIssueDate',
      type: 'text',
      x: 74.5,
      y: 58.59,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 20,
    },

    // Row 4: License Expiry Date / تاريخ الانتهاء (y: 61.13%)
    {
      id: 'f-tga-licexp-en',
      name: 'License Expiry Date (EN)',
      key: 'licenseExpiryDate',
      type: 'text',
      x: 25.42,
      y: 61.13,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 21,
    },
    {
      id: 'f-tga-licexp-ar',
      name: 'تاريخ انتهاء الترخيص (AR)',
      key: 'licenseExpiryDate',
      type: 'text',
      x: 74.5,
      y: 61.13,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 22,
    },

    // Row 5: Activity Type / نوع النشاط (y: 63.48%)
    {
      id: 'f-tga-act-en',
      name: 'Activity Type (EN)',
      key: 'activityTypeEn',
      type: 'text',
      x: 25.42,
      y: 63.48,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 10.5,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 23,
    },
    {
      id: 'f-tga-act-ar',
      name: 'نوع النشاط (AR)',
      key: 'activityTypeAr',
      type: 'text',
      x: 74.5,
      y: 63.48,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 10.5,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 24,
    },

    // Row 6: MOI Number / رقم هوية المنشأة (y: 66.11%)
    {
      id: 'f-tga-moi-en',
      name: 'MOI Number (EN)',
      key: 'moiNumber',
      type: 'text',
      x: 25.42,
      y: 66.11,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 25,
    },
    {
      id: 'f-tga-moi-ar',
      name: 'رقم هوية المنشأة (AR)',
      key: 'moiNumber',
      type: 'text',
      x: 74.5,
      y: 66.11,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 26,
    },

    // Row 7: Company Name / اسم المنشأة (y: 68.65%)
    {
      id: 'f-tga-comp-en',
      name: 'Company Name (EN)',
      key: 'company',
      type: 'text',
      x: 25.42,
      y: 68.65,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 27,
    },
    {
      id: 'f-tga-comp-ar',
      name: 'اسم المنشأة (AR)',
      key: 'companyAr',
      type: 'text',
      x: 74.5,
      y: 68.65,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 28,
    },
  ],
};

const opText = (
  id: string,
  name: string,
  key: string,
  x: number,
  y: number,
  zIndex: number,
  opts: Partial<TemplateField> = {}
): TemplateField => ({
  id,
  name,
  key,
  type: 'text',
  x,
  y,
  width: 25,
  fontFamily: 'Almarai',
  fontSize: 10.5,
  fontWeight: '400',
  fontStyle: 'normal',
  color: '#33373b',
  textAlign: x > 50 ? 'right' : 'left',
  textTransform: 'none',
  letterSpacing: 0,
  lineHeight: 1.2,
  opacity: 1,
  zIndex,
  ...opts,
});

export const SAUDI_OPERATION_CARD_TEMPLATE: Template = {
  id: 'saudi-tga-operation-card',
  name: 'بطاقة تشغيل - Saudi TGA Operation Card',
  category: 'badge',
  imageUrl: '/templates/saudi-operation-card-blank.png',
  naturalWidth: 1110,
  naturalHeight: 1604,
  createdAt: Date.now(),
  fields: [
    // Top Left Dynamic QR Code
    {
      id: 'f-op-qr',
      name: 'رمز الاستجابة السريعة (QR Code)',
      key: 'operationCardQr',
      type: 'qr',
      x: 16.67,
      y: 11.78,
      width: 13.51,
      height: 9.35,
      fontFamily: 'Almarai',
      fontSize: 12,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#000000',
      textAlign: 'center',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1,
      opacity: 1,
      backgroundColor: '#ffffff',
      zIndex: 1,
    },

    // SECTION 1: Organization Info / بيانات المنشأة
    // Row 1: ID Number / رقم الهوية (y: 24.45%)
    opText('f-op-org-id-en', 'Organization ID (EN)', 'moiNumber', 25.5, 24.45, 2),
    opText('f-op-org-id-ar', 'رقم هوية المنشأة (AR)', 'moiNumber', 74.7, 24.45, 3),

    // Row 2: Name / الاسم (y: 27.03%)
    opText('f-op-org-name-en', 'Organization Name (EN)', 'companyEn', 25.5, 27.03, 4, { width: 28 }),
    opText('f-op-org-name-ar', 'اسم المنشأة (AR)', 'companyAr', 74.7, 27.03, 5, { width: 28 }),

    // SECTION 2: Operation Card Info / بيانات بطاقة التشغيل
    // Row 1: Card Number / رقم البطاقة (y: 38.03%)
    opText('f-op-cardno-en', 'Card Number (EN)', 'operationCardNo', 25.5, 38.03, 6),
    opText('f-op-cardno-ar', 'رقم البطاقة (AR)', 'operationCardNo', 74.7, 38.03, 7),

    // Row 2: Card Issue Date / تاريخ إصدار البطاقة (y: 40.67%)
    opText('f-op-card-issue-en', 'Issue Date (EN)', 'operationCardIssueDate', 25.5, 40.67, 8),
    opText('f-op-card-issue-ar', 'تاريخ إصدار البطاقة (AR)', 'operationCardIssueDate', 74.7, 40.67, 9),

    // Row 3: Card Expiry Date / تاريخ انتهاء البطاقة (y: 43.17%)
    opText('f-op-card-expiry-en', 'Expiry Date (EN)', 'operationCardExpiryDate', 25.5, 43.17, 10),
    opText('f-op-card-expiry-ar', 'تاريخ انتهاء البطاقة (AR)', 'operationCardExpiryDate', 74.7, 43.17, 11),

    // Row 4: Card Renew Date / تاريخ تجديد البطاقة (y: 45.66%)
    opText('f-op-card-renew-en', 'Renew Date (EN)', 'operationCardRenewDate', 25.5, 45.66, 12),
    opText('f-op-card-renew-ar', 'تاريخ تجديد البطاقة (AR)', 'operationCardRenewDate', 74.7, 45.66, 13),

    // SECTION 3: Vehicle Info / بيانات المركبة
    // Row 1: Maker / الماركة (y: 56.93%)
    opText('f-op-veh-maker-en', 'Maker (Left)', 'vehicleMaker', 25.5, 56.93, 14),
    opText('f-op-veh-maker-ar', 'الماركة (Right)', 'vehicleMaker', 74.7, 56.93, 15),

    // Row 2: Model / الطراز (y: 59.53%)
    opText('f-op-veh-model-en', 'Model (Left)', 'vehicleModel', 25.5, 59.53, 16),
    opText('f-op-veh-model-ar', 'الطراز (Right)', 'vehicleModel', 74.7, 59.53, 17),

    // Row 3: Plate Number / رقم اللوحة (y: 61.85%)
    opText('f-op-veh-plate-en', 'Plate Number (Left)', 'plateNumber', 25.5, 61.85, 18),
    opText('f-op-veh-plate-ar', 'رقم اللوحة (Right)', 'plateNumber', 74.7, 61.85, 19),

    // Row 4: Color / لون المركبة (y: 64.68%)
    opText('f-op-veh-color-en', 'Color (Left)', 'vehicleColor', 25.5, 64.68, 20),
    opText('f-op-veh-color-ar', 'لون المركبة (Right)', 'vehicleColor', 74.7, 64.68, 21),

    // Row 5: Model Year / سنة الصنع (y: 67.31%)
    opText('f-op-veh-year-en', 'Model Year (Left)', 'vehicleYear', 25.5, 67.31, 22),
    opText('f-op-veh-year-ar', 'سنة الصنع (Right)', 'vehicleYear', 74.7, 67.31, 23),

    // SECTION 4: License Info / بيانات الترخيص
    // Row 1: License Number / رقم الترخيص (y: 78.08%)
    opText('f-op-lic-no-en', 'License Number (Left)', 'licenseNumber', 25.5, 78.08, 24),
    opText('f-op-lic-no-ar', 'رقم الترخيص (Right)', 'licenseNumber', 74.7, 78.08, 25),

    // Row 2: License City / مدينة الترخيص (y: 80.57%)
    opText('f-op-lic-city-en', 'License City (EN)', 'cityEn', 25.5, 80.57, 26),
    opText('f-op-lic-city-ar', 'مدينة الترخيص (AR)', 'cityAr', 74.7, 80.57, 27),

    // Row 3: Issue Date / تاريخ إصدار الترخيص (y: 83.07%)
    opText('f-op-lic-issue-en', 'License Issue Date (Left)', 'licenseIssueDate', 25.5, 83.07, 28),
    opText('f-op-lic-issue-ar', 'تاريخ إصدار الترخيص (Right)', 'licenseIssueDate', 74.7, 83.07, 29),

    // Row 4: Expiry Date / تاريخ انتهاء الترخيص (y: 85.56%)
    opText('f-op-lic-exp-en', 'License Expiry Date (Left)', 'licenseExpiryDate', 25.5, 85.56, 30),
    opText('f-op-lic-exp-ar', 'تاريخ انتهاء الترخيص (Right)', 'licenseExpiryDate', 74.7, 85.56, 31),
  ],
};

export const DEFAULT_TEMPLATES: Template[] = [
  SAUDI_DRIVING_LICENSE_TEMPLATE,
  SAUDI_MUQEEM_ID_TEMPLATE,
  SAUDI_DRIVER_CARD_TEMPLATE,
  SAUDI_OPERATION_CARD_TEMPLATE,
];

