import { Template } from '../types/template';

export const SAUDI_DRIVING_LICENSE_TEMPLATE: Template = {
  id: 'saudi-driving-license',
  name: 'رخصة سياقة - Driving License',
  category: 'badge',
  imageUrl: '/templates/saudi-driving-license-blank.jpg',
  naturalWidth: 952,
  naturalHeight: 578,
  createdAt: Date.now(),
  fields: [
    // 1. Personal Photo in the left white box (63px to 298px, 145px to 423px)
    {
      id: 'dl-photo',
      name: 'الصورة الشخصية (Photo)',
      key: 'photo',
      type: 'image',
      x: 18.96,
      y: 49.14,
      width: 24.68,
      height: 48.1,
      fontFamily: 'Almarai',
      fontSize: 12,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#000000',
      textAlign: 'center',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1,
      opacity: 1,
      imageShape: 'rect',
      zIndex: 1,
    },

    // 2. Arabic Name (Top right, prominent bold)
    {
      id: 'dl-name-ar',
      name: 'الاسم بالعربية (Arabic Name)',
      key: 'nameAr',
      type: 'text',
      x: 84.5,
      y: 29.5,
      width: 55,
      fontFamily: 'Almarai',
      fontSize: 25.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 2,
    },

    // 3. English Name (Under Arabic name, full span)
    {
      id: 'dl-name-en',
      name: 'الاسم بالإنجليزية (English Name)',
      key: 'nameEn',
      type: 'text',
      x: 84.5,
      y: 36.2,
      width: 60,
      fontFamily: 'Inter',
      fontSize: 16.5,
      fontWeight: '500',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'uppercase',
      letterSpacing: 0.3,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 3,
    },

    // Row 1: ID Number (y: 40.66%)
    {
      id: 'dl-id-en',
      name: 'ID Number (EN)',
      key: 'idNumberEn',
      type: 'text',
      x: 48.0,
      y: 40.66,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 15.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 4,
    },
    {
      id: 'dl-id-ar',
      name: 'رقم الهوية (AR)',
      key: 'idNumberAr',
      type: 'text',
      x: 84.0,
      y: 40.66,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 15.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 5,
    },

    // Row 2: License Type (y: 48.62%)
    {
      id: 'dl-lictype-en',
      name: 'License Type (EN)',
      key: 'licenseTypeEn',
      type: 'text',
      x: 48.0,
      y: 48.62,
      width: 32,
      fontFamily: 'Almarai',
      fontSize: 15,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 6,
    },
    {
      id: 'dl-lictype-ar',
      name: 'نوع الرخصة (AR)',
      key: 'licenseTypeAr',
      type: 'text',
      x: 84.0,
      y: 48.62,
      width: 32,
      fontFamily: 'Almarai',
      fontSize: 15.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 7,
    },

    // Row 3: Issue Date (y: 57.09%)
    {
      id: 'dl-issue-en',
      name: 'Issue Date (EN)',
      key: 'issueDateEn',
      type: 'text',
      x: 48.0,
      y: 57.09,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 15,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 8,
    },
    {
      id: 'dl-issue-ar',
      name: 'تاريخ الإصدار (AR)',
      key: 'issueDateAr',
      type: 'text',
      x: 84.0,
      y: 57.09,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 15.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 9,
    },

    // Row 4: Date of Birth (y: 65.22%)
    {
      id: 'dl-dob-en',
      name: 'Date of Birth (EN)',
      key: 'dobEn',
      type: 'text',
      x: 48.0,
      y: 65.22,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 15,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 10,
    },
    {
      id: 'dl-dob-ar',
      name: 'تاريخ الميلاد (AR)',
      key: 'dobAr',
      type: 'text',
      x: 84.0,
      y: 65.22,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 15.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 11,
    },

    // Row 5: Nationality (y: 74.22%)
    {
      id: 'dl-nation-en',
      name: 'Nationality (EN)',
      key: 'nationalityEn',
      type: 'text',
      x: 48.0,
      y: 74.22,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 15,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 12,
    },
    {
      id: 'dl-nation-ar',
      name: 'الجنسية (AR)',
      key: 'nationalityAr',
      type: 'text',
      x: 84.0,
      y: 74.22,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 15.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 13,
    },

    // Row 6: Expiry Date (y: 81.66%)
    {
      id: 'dl-exp-en',
      name: 'Expiry Date (EN)',
      key: 'expiryDateEn',
      type: 'text',
      x: 48.0,
      y: 81.66,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 15,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 14,
    },
    {
      id: 'dl-exp-ar',
      name: 'تاريخ الانتهاء (AR)',
      key: 'expiryDateAr',
      type: 'text',
      x: 84.0,
      y: 81.66,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 15.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 15,
    },

    // Row 7: Blood Type (y: 88.06%)
    {
      id: 'dl-blood-en',
      name: 'Blood Type (EN)',
      key: 'bloodType',
      type: 'text',
      x: 48.0,
      y: 88.06,
      width: 18,
      fontFamily: 'Almarai',
      fontSize: 15,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 16,
    },
    {
      id: 'dl-blood-ar',
      name: 'فصيلة الدم (AR)',
      key: 'bloodType',
      type: 'text',
      x: 84.0,
      y: 88.06,
      width: 18,
      fontFamily: 'Almarai',
      fontSize: 15.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 17,
    },
  ],
};

export const SAUDI_MUQEEM_ID_TEMPLATE: Template = {
  id: 'saudi-muqeem-id',
  name: 'هوية مقيم - Muqeem ID',
  category: 'badge',
  imageUrl: '/templates/saudi-muqeem-id-blank.jpg',
  naturalWidth: 952,
  naturalHeight: 578,
  createdAt: Date.now(),
  fields: [
    // 1. Personal Photo in the left white box
    {
      id: 'mq-photo',
      name: 'الصورة الشخصية (Photo)',
      key: 'photo',
      type: 'image',
      x: 18.96,
      y: 49.14,
      width: 24.68,
      height: 48.1,
      fontFamily: 'Almarai',
      fontSize: 12,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#000000',
      textAlign: 'center',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1,
      opacity: 1,
      imageShape: 'rect',
      zIndex: 1,
    },

    // 2. Arabic Name (Top right, prominent bold)
    {
      id: 'mq-name-ar',
      name: 'الاسم بالعربية (Arabic Name)',
      key: 'nameAr',
      type: 'text',
      x: 84.5,
      y: 33.0,
      width: 55,
      fontFamily: 'Almarai',
      fontSize: 25.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 2,
    },

    // 3. English Name (Under Arabic name, full span)
    {
      id: 'mq-name-en',
      name: 'الاسم بالإنجليزية (English Name)',
      key: 'nameEn',
      type: 'text',
      x: 84.5,
      y: 39.5,
      width: 60,
      fontFamily: 'Inter',
      fontSize: 16.5,
      fontWeight: '500',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'uppercase',
      letterSpacing: 0.3,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 3,
    },

    // Middle Column Fields:
    // Expiry Date (y: 43.43%)
    {
      id: 'mq-expiry',
      name: 'تاريخ الانتهاء (Expiry Date)',
      key: 'expiryDateAr',
      type: 'text',
      x: 49.5,
      y: 43.43,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 14.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 4,
    },
    // Place of Birth (y: 50.00%)
    {
      id: 'mq-pob',
      name: 'مكان الميلاد (Place of Birth)',
      key: 'pobAr',
      type: 'text',
      x: 49.0,
      y: 50.0,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 14.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 5,
    },
    // Religion (y: 56.40%)
    {
      id: 'mq-rel',
      name: 'الديانة (Religion)',
      key: 'religionAr',
      type: 'text',
      x: 53.5,
      y: 56.4,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 14.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 6,
    },

    // Right Column Fields:
    // ID Number (y: 43.43%)
    {
      id: 'mq-id',
      name: 'رقم الهوية (ID Number)',
      key: 'idNumberAr',
      type: 'text',
      x: 84.5,
      y: 43.43,
      width: 30,
      fontFamily: 'Almarai',
      fontSize: 15.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 7,
    },
    // Date of Birth (y: 49.83%)
    {
      id: 'mq-dob',
      name: 'تاريخ الميلاد (Date of Birth)',
      key: 'dobAr',
      type: 'text',
      x: 84.0,
      y: 49.83,
      width: 30,
      fontFamily: 'Almarai',
      fontSize: 14.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 8,
    },
    // Nationality (y: 56.40%)
    {
      id: 'mq-nation',
      name: 'الجنسية (Nationality)',
      key: 'nationalityAr',
      type: 'text',
      x: 87.0,
      y: 56.4,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 14.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 9,
    },
    // Profession (y: 63.67%)
    {
      id: 'mq-job',
      name: 'المهنة (Profession)',
      key: 'professionAr',
      type: 'text',
      x: 88.0,
      y: 63.67,
      width: 40,
      fontFamily: 'Almarai',
      fontSize: 14.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 10,
    },
    // Employer ID (y: 70.24%)
    {
      id: 'mq-empid',
      name: 'هوية صاحب العمل (Employer ID)',
      key: 'employerIdAr',
      type: 'text',
      x: 78.0,
      y: 70.24,
      width: 30,
      fontFamily: 'Almarai',
      fontSize: 15.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 11,
    },
    // Place of Issue (y: 76.64%)
    {
      id: 'mq-issueplace',
      name: 'مكان الإصدار (Place of Issue)',
      key: 'issuePlaceAr',
      type: 'text',
      x: 83.0,
      y: 76.64,
      width: 45,
      fontFamily: 'Almarai',
      fontSize: 13.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 12,
    },
    // Place of Work (y: 83.22%)
    {
      id: 'mq-workplace',
      name: 'مكان العمل (Place of Work)',
      key: 'workPlaceAr',
      type: 'text',
      x: 82.5,
      y: 83.22,
      width: 35,
      fontFamily: 'Almarai',
      fontSize: 14.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 13,
    },
    // Employer Name (y: 89.62%)
    {
      id: 'mq-empname',
      name: 'اسم صاحب العمل (Employer Name)',
      key: 'employerNameAr',
      type: 'text',
      x: 78.0,
      y: 89.62,
      width: 45,
      fontFamily: 'Almarai',
      fontSize: 14.5,
      fontWeight: '700',
      fontStyle: 'normal',
      color: '#111827',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 14,
    },
  ],
};

export const SAUDI_DRIVER_CARD_TEMPLATE: Template = {
  id: 'saudi-tga-driver-card',
  name: 'بطاقة سائق - Saudi TGA Driver Card',
  category: 'badge',
  imageUrl: '/templates/saudi-driver-card-blank.png',
  naturalWidth: 708,
  naturalHeight: 1024,
  createdAt: Date.now(),
  fields: [
    // Top Header Card Subtitle: "بطاقة رقم 38.00057886" centered at x=50.0%
    {
      id: 'f-tga-topcardno',
      name: 'رقم البطاقة العلوي (Header Card Number)',
      key: 'code',
      type: 'text',
      x: 50.0,
      y: 13.8,
      width: 40,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#64748b',
      textAlign: 'center',
      textTransform: 'none',
      letterSpacing: 0.2,
      lineHeight: 1.2,
      opacity: 1,
      prefix: 'بطاقة رقم ',
      zIndex: 2,
    },

    // SECTION 1: Driver Card Info / بيانات بطاقة السائق
    // Row 1: Driver Card Number (y: 27.54%)
    {
      id: 'f-tga-cardno-en',
      name: 'Card Number (EN)',
      key: 'code',
      type: 'text',
      x: 25.42,
      y: 27.54,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 3,
    },
    {
      id: 'f-tga-cardno-ar',
      name: 'رقم بطاقة السائق (AR)',
      key: 'code',
      type: 'text',
      x: 74.5,
      y: 27.54,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 4,
    },

    // Row 2: Driver Name (y: 30.2%)
    {
      id: 'f-tga-name-en',
      name: 'Driver Name (Left)',
      key: 'name',
      type: 'text',
      x: 25.42,
      y: 30.2,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 5,
    },
    {
      id: 'f-tga-name-ar',
      name: 'اسم السائق (Right)',
      key: 'name',
      type: 'text',
      x: 74.5,
      y: 30.2,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 6,
    },

    // Row 3: Driver Id / رقم هوية السائق (y: 32.42%)
    {
      id: 'f-tga-id-en',
      name: 'Driver Id (EN)',
      key: 'driverId',
      type: 'text',
      x: 25.42,
      y: 32.42,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 7,
    },
    {
      id: 'f-tga-id-ar',
      name: 'رقم هوية السائق (AR)',
      key: 'driverId',
      type: 'text',
      x: 74.5,
      y: 32.42,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 8,
    },

    // Row 4: Issue Date / تاريخ الإصدار (y: 34.86%)
    {
      id: 'f-tga-issue-en',
      name: 'Issue Date (EN)',
      key: 'date',
      type: 'text',
      x: 25.42,
      y: 34.86,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 9,
    },
    {
      id: 'f-tga-issue-ar',
      name: 'تاريخ الإصدار (AR)',
      key: 'date',
      type: 'text',
      x: 74.5,
      y: 34.86,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 10,
    },

    // Row 5: Expiration Date / تاريخ الانتهاء (y: 37.4%)
    {
      id: 'f-tga-expiry-en',
      name: 'Expiration Date (EN)',
      key: 'expiryDate',
      type: 'text',
      x: 25.42,
      y: 37.4,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 11,
    },
    {
      id: 'f-tga-expiry-ar',
      name: 'تاريخ الانتهاء (AR)',
      key: 'expiryDate',
      type: 'text',
      x: 74.5,
      y: 37.4,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 12,
    },

    // Row 6: Card Category / تصنيف البطاقة (y: 40.04%)
    {
      id: 'f-tga-cat-en',
      name: 'Card Category (EN)',
      key: 'cardCategoryEn',
      type: 'text',
      x: 25.42,
      y: 40.04,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 13,
    },
    {
      id: 'f-tga-cat-ar',
      name: 'تصنيف البطاقة (AR)',
      key: 'cardCategoryAr',
      type: 'text',
      x: 74.5,
      y: 40.04,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 14,
    },

    // SECTION 2: License and Company Info / بيانات المنشأة و الترخيص
    // Row 1: License Number / رقم الترخيص (y: 53.61%)
    {
      id: 'f-tga-licno-en',
      name: 'License Number (EN)',
      key: 'licenseNumber',
      type: 'text',
      x: 25.42,
      y: 53.61,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 15,
    },
    {
      id: 'f-tga-licno-ar',
      name: 'رقم الترخيص (AR)',
      key: 'licenseNumber',
      type: 'text',
      x: 74.5,
      y: 53.61,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 16,
    },

    // Row 2: License City / مدينة الترخيص (y: 56.15%)
    {
      id: 'f-tga-city-en',
      name: 'License City (EN)',
      key: 'cityEn',
      type: 'text',
      x: 25.42,
      y: 56.15,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 17,
    },
    {
      id: 'f-tga-city-ar',
      name: 'مدينة الترخيص (AR)',
      key: 'cityAr',
      type: 'text',
      x: 74.5,
      y: 56.15,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 18,
    },

    // Row 3: License Issue Date / تاريخ الإصدار (y: 58.59%)
    {
      id: 'f-tga-licissue-en',
      name: 'License Issue Date (EN)',
      key: 'licenseIssueDate',
      type: 'text',
      x: 25.42,
      y: 58.59,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 19,
    },
    {
      id: 'f-tga-licissue-ar',
      name: 'تاريخ إصدار الترخيص (AR)',
      key: 'licenseIssueDate',
      type: 'text',
      x: 74.5,
      y: 58.59,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 20,
    },

    // Row 4: License Expiry Date / تاريخ الانتهاء (y: 61.13%)
    {
      id: 'f-tga-licexp-en',
      name: 'License Expiry Date (EN)',
      key: 'licenseExpiryDate',
      type: 'text',
      x: 25.42,
      y: 61.13,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 21,
    },
    {
      id: 'f-tga-licexp-ar',
      name: 'تاريخ انتهاء الترخيص (AR)',
      key: 'licenseExpiryDate',
      type: 'text',
      x: 74.5,
      y: 61.13,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 22,
    },

    // Row 5: Activity Type / نوع النشاط (y: 63.48%)
    {
      id: 'f-tga-act-en',
      name: 'Activity Type (EN)',
      key: 'activityTypeEn',
      type: 'text',
      x: 25.42,
      y: 63.48,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 10.5,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 23,
    },
    {
      id: 'f-tga-act-ar',
      name: 'نوع النشاط (AR)',
      key: 'activityTypeAr',
      type: 'text',
      x: 74.5,
      y: 63.48,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 10.5,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 24,
    },

    // Row 6: MOI Number / رقم هوية المنشأة (y: 66.11%)
    {
      id: 'f-tga-moi-en',
      name: 'MOI Number (EN)',
      key: 'moiNumber',
      type: 'text',
      x: 25.42,
      y: 66.11,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 25,
    },
    {
      id: 'f-tga-moi-ar',
      name: 'رقم هوية المنشأة (AR)',
      key: 'moiNumber',
      type: 'text',
      x: 74.5,
      y: 66.11,
      width: 25,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 26,
    },

    // Row 7: Company Name / اسم المنشأة (y: 68.65%)
    {
      id: 'f-tga-comp-en',
      name: 'Company Name (EN)',
      key: 'company',
      type: 'text',
      x: 25.42,
      y: 68.65,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'left',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 27,
    },
    {
      id: 'f-tga-comp-ar',
      name: 'اسم المنشأة (AR)',
      key: 'companyAr',
      type: 'text',
      x: 74.5,
      y: 68.65,
      width: 28,
      fontFamily: 'Almarai',
      fontSize: 11,
      fontWeight: '400',
      fontStyle: 'normal',
      color: '#33373b',
      textAlign: 'right',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      opacity: 1,
      zIndex: 28,
    },
  ],
};

export const DEFAULT_TEMPLATES: Template[] = [
  SAUDI_DRIVING_LICENSE_TEMPLATE,
  SAUDI_MUQEEM_ID_TEMPLATE,
  SAUDI_DRIVER_CARD_TEMPLATE,
];
