import { PersonRecord } from '../types/template';

export const INITIAL_PEOPLE: PersonRecord[] = [
  {
    id: 'driver-1',
    name: 'احمد حسين محمد حسين مهدي',
    title: 'Professional Driver / سائق نقل خفيف',
    date: '2026-06-07',
    code: '38.00057886',
    company: 'Ghada Company Commercial',
    email: 'ahmed.mahdi@ghada.sa',
    isSelected: true,
    customFields: {
      driverId: '2628113686',
      expiryDate: '2027-06-09',
      cardCategoryEn: 'Yearly',
      cardCategoryAr: 'سنوية',
      licenseNumber: '38/00021153',
      cityEn: 'Tabuk',
      cityAr: 'تبوك',
      licenseIssueDate: '2025-12-08',
      licenseExpiryDate: '2028-12-08',
      activityTypeEn: 'Light cargo transport activity',
      activityTypeAr: 'نشاط النقل الخفيف للبضائع',
      moiNumber: '7037427601',
      companyAr: 'شركة غضى التجارية',
    },
  },
  {
    id: 'driver-2',
    name: 'سعود فهد عبدالله الشمري',
    title: 'Professional Driver / سائق نقل خفيف',
    date: '2026-07-01',
    code: '38.00057887',
    company: 'Al-Riyadh Logistics Transport',
    email: 'saud.alshammari@riyadhlog.sa',
    isSelected: true,
    customFields: {
      driverId: '1084920184',
      expiryDate: '2027-07-01',
      cardCategoryEn: 'Yearly',
      cardCategoryAr: 'سنوية',
      licenseNumber: '38/00029941',
      cityEn: 'Riyadh',
      cityAr: 'الرياض',
      licenseIssueDate: '2026-01-10',
      licenseExpiryDate: '2029-01-10',
      activityTypeEn: 'Light cargo transport activity',
      activityTypeAr: 'نشاط النقل الخفيف للبضائع',
      moiNumber: '7011928472',
      companyAr: 'شركة الرياض للنقل اللوجستي',
    },
  },
  {
    id: 'driver-3',
    name: 'محمد خالد عمر باوزير',
    title: 'Heavy Transport Driver / سائق نقل ثقيل',
    date: '2026-08-15',
    code: '38.00057888',
    company: 'Red Sea Express Services',
    email: 'm.bawazir@redseaexpress.sa',
    isSelected: true,
    customFields: {
      driverId: '1058291049',
      expiryDate: '2027-08-15',
      cardCategoryEn: 'Yearly',
      cardCategoryAr: 'سنوية',
      licenseNumber: '38/00031852',
      cityEn: 'Jeddah',
      cityAr: 'جدة',
      licenseIssueDate: '2026-02-15',
      licenseExpiryDate: '2029-02-15',
      activityTypeEn: 'Heavy cargo transport activity',
      activityTypeAr: 'نشاط النقل الثقيل للبضائع',
      moiNumber: '7028194018',
      companyAr: 'مؤسسة البحر الأحمر للخدمات',
    },
  },
];
