import { PersonRecord } from '../types/template';

export const INITIAL_PEOPLE: PersonRecord[] = [
  {
    id: 'driver-eslam',
    name: 'اسلام حماده فؤاد عبد الرحمن',
    title: 'سائق نقل خفيف / Light Transport Driver',
    date: '2026/04/02',
    code: '2579236403',
    company: 'شركة غضى التجارية',
    email: 'eslam.fouad@ghada.sa',
    photoUrl: '/templates/sample-person.jpg',
    isSelected: true,
    customFields: {
      nameAr: 'اسلام حماده فؤاد عبد الرحمن',
      nameEn: 'ESLAM HAMADA FOUAD ABDELRAHMAN',
      driverId: '2579236403',
      idNumberEn: '2579236403',
      idNumberAr: '٢٥٧٩٢٣٦٤٠٣',
      licenseTypeEn: 'Light Transport',
      licenseTypeAr: 'نقل خفيف',
      issueDateEn: '02/04/2026',
      issueDateAr: '٢٠٢٦/٠٤/٠٢',
      dobEn: '01/12/1999',
      dobAr: '١٩٩٩/١٢/٠١',
      nationalityEn: 'Egypt',
      nationalityAr: 'مصر',
      expiryDateEn: '06/02/2031',
      expiryDateAr: '٢٠٣١/٠٢/٠٦',
      bloodType: 'A+',
      // Muqeem ID specific fields
      pobAr: 'مصر',
      religionAr: 'الاسلام',
      professionAr: 'سائق شاحنة صغيرة',
      employerIdAr: '٧٠٣٧٤٢٧٦٠١',
      issuePlaceAr: 'موقع بوابة الوزارة الإلكترونية',
      workPlaceAr: 'منطقة تبوك',
      employerNameAr: 'شركة غضى التجارية',
      // TGA Driver Card fields
      expiryDate: '2027-06-09',
      cardCategoryEn: 'Yearly',
      cardCategoryAr: 'سنوية',
      licenseNumber: '38/00021153',
      cityEn: 'Tabuk',
      cityAr: 'تبوك',
      licenseIssueDate: '2025-12-08',
      licenseExpiryDate: '2028-12-08',
      activityTypeEn: 'Light cargo transport activity',
      activityTypeAr: 'نشاط النقل الخفيف للبضائع',
      moiNumber: '7037427601',
      companyAr: 'شركة غضى لتأجير السيارات',
      companyEn: 'Ghada Company Cars Rental',
      // TGA Operation Card fields
      operationCardNo: '38-00075448',
      operationCardIssueDate: '2026-04-27',
      operationCardExpiryDate: '2027-04-29',
      operationCardRenewDate: 'null',
      vehicleMaker: 'سوزوكي',
      vehicleModel: 'ديز اير',
      plateNumber: '8781 أ أ ر',
      vehicleColor: 'فضي',
      vehicleYear: '2024',
      operationCardQr: 'https://naql.logisti.sa/validate-operation-card?token=12aeed0c-87b8-4adc-8147-49b3d4d8901d',
    },
  },
  {
    id: 'driver-ahmed',
    name: 'احمد حسين محمد حسين مهدي',
    title: 'سائق نقل خفيف / Professional Driver',
    date: '2026/06/07',
    code: '2628113686',
    company: 'شركة غضى التجارية',
    email: 'ahmed.mahdi@ghada.sa',
    photoUrl: '/templates/sample-person.jpg',
    isSelected: true,
    customFields: {
      nameAr: 'احمد حسين محمد حسين مهدي',
      nameEn: 'AHMED HUSSEIN MOHAMED HUSSEIN MAHDI',
      driverId: '2628113686',
      idNumberEn: '2628113686',
      idNumberAr: '٢٦٢٨١١٣٦٨٦',
      licenseTypeEn: 'Light Transport',
      licenseTypeAr: 'نقل خفيف',
      issueDateEn: '07/06/2026',
      issueDateAr: '٢٠٢٦/٠٦/٠٧',
      dobEn: '15/05/1995',
      dobAr: '١٩٩٥/٠٥/١٥',
      nationalityEn: 'Yemen',
      nationalityAr: 'اليمن',
      expiryDateEn: '07/06/2031',
      expiryDateAr: '٢٠٣١/٠٦/٠٧',
      bloodType: 'O+',
      pobAr: 'اليمن',
      religionAr: 'الاسلام',
      professionAr: 'سائق نقل بضائع',
      employerIdAr: '٧٠٣٧٤٢٧٦٠١',
      issuePlaceAr: 'موقع بوابة الوزارة الإلكترونية',
      workPlaceAr: 'منطقة تبوك',
      employerNameAr: 'شركة غضى التجارية',
      expiryDate: '2027-06-09',
      cardCategoryEn: 'Yearly',
      cardCategoryAr: 'سنوية',
      licenseNumber: '38/00021153',
      cityEn: 'Tabuk',
      cityAr: 'تبوك',
      licenseIssueDate: '2025-12-08',
      licenseExpiryDate: '2028-12-08',
      activityTypeEn: 'Light cargo transport activity',
      activityTypeAr: 'نشاط النقل الخفيف للبضائع',
      moiNumber: '7037427601',
      companyAr: 'شركة غضى التجارية',
      companyEn: 'Ghada Company Commercial',
    },
  },
  {
    id: 'driver-saud',
    name: 'سعود فهد عبدالله الشمري',
    title: 'سائق نقل خفيف / Professional Driver',
    date: '2026/07/01',
    code: '1084920184',
    company: 'شركة الرياض للنقل اللوجستي',
    email: 'saud.alshammari@riyadhlog.sa',
    photoUrl: '/templates/sample-person.jpg',
    isSelected: true,
    customFields: {
      nameAr: 'سعود فهد عبدالله الشمري',
      nameEn: 'SAUD FAHAD ABDULLAH ALSHAMMARI',
      driverId: '1084920184',
      idNumberEn: '1084920184',
      idNumberAr: '١٠٨٤٩٢٠١٨٤',
      licenseTypeEn: 'Private Transport',
      licenseTypeAr: 'نقل خاص',
      issueDateEn: '01/07/2026',
      issueDateAr: '٢٠٢٦/٠٧/٠١',
      dobEn: '20/03/1998',
      dobAr: '١٩٩٨/٠٣/٢٠',
      nationalityEn: 'Saudi',
      nationalityAr: 'سعودي',
      expiryDateEn: '01/07/2036',
      expiryDateAr: '٢٠٣٦/٠٧/٠١',
      bloodType: 'B+',
      pobAr: 'الرياض',
      religionAr: 'الاسلام',
      professionAr: 'سائق',
      employerIdAr: '٧٠١١٩٢٨٤٧٢',
      issuePlaceAr: 'موقع بوابة الوزارة الإلكترونية',
      workPlaceAr: 'منطقة الرياض',
      employerNameAr: 'شركة الرياض للنقل اللوجستي',
      expiryDate: '2027-07-01',
      cardCategoryEn: 'Yearly',
      cardCategoryAr: 'سنوية',
      licenseNumber: '38/00029941',
      cityEn: 'Riyadh',
      cityAr: 'الرياض',
      licenseIssueDate: '2026-01-10',
      licenseExpiryDate: '2029-01-10',
      activityTypeEn: 'Light cargo transport activity',
      activityTypeAr: 'نشاط النقل الخفيف للبضائع',
      moiNumber: '7011928472',
      companyAr: 'شركة الرياض للنقل اللوجستي',
      companyEn: 'Riyadh Logistics Transport Co',
    },
  },
];
